//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AU2.rc
//
#define IDC_USER_SAVE                   3
#define IDC_USER_LOAD                   4
#define ID_REPLACE_YESTOALL             7
#define ID_REPLACE_NO                   8
#define IDD_ABOUTBOX                    100
#define IDD_AU2_FORM                    101
#define IDR_MAINFRAME                   128
#define IDR_AU2TYPE                     129
#define IDD_AU2_FORM2                   131
#define IDB_ROSETTE                     132
#define IDD_UPGRADEHBXDLG               134
#define IDB_MEADE_LOGO                  135
#define IDD_REPLACE_DLG                 135
#define IDB_TITLE                       136
#define IDD_SELECT_DLG                  136
#define IDD_SATELLITE_DLG               138
#define IDD_EDITOBJECTS                 139
#define IDD_COMPORT_DLG                 140
#define IDD_ALL_DLG                     142
#define IDD_TRANSFERLOG_DLG             143
#define IDR_MENU2                       145
#define IDR_TOOLBAR1                    148
#define IDD_ERRORLOG_DLG                149
#define IDD_POPUP_USEROBJ               153
#define IDD_POPUP_USEROBJ2              154
#define IDD_DEFINECATALOG_DLG           155
#define IDD_USERSITE_DLG                157
#define ID_EXIT                         1002
#define IDC_BUTTON_RESTART              1003
#define IDC_BUTTON_CONNECT              1004
#define IDC_LIBRARY                     1005
#define IDC_HANDBOX                     1006
#define IDC_UPGRADE                     1007
#define IDC_ADVANCED                    1010
#define IDC_BUTTON_SEND                 1011
#define IDC_BUTTON_TOHBX                1012
#define IDC_BUTTON_TOLIB                1013
#define IDC_BUTTON_RETRIEVE             1014
#define IDC_BUTTON_REFRESH              1015
#define IDC_BUTTON_TOLIB_ALL            1016
#define IDC_EDITTERLABEL                1017
#define IDC_BUTTON_TOLIB_REFRESH        1017
#define IDC_VERSION                     1019
#define IDS_VERSION                     1019
#define IDC_UPGRADE_WWW                 1020
#define IDC_UPGRADE_HD                  1021
#define IDC_UPGRADE_WWW_TEXT            1022
#define IDC_UPGRADE_HD_TEXT             1023
#define IDC_UPGRADE_HBX_TEXT            1025
#define ID_REPLACE_YES                  1027
#define IDC_REPLACE_OBJECT              1028
#define IDC_LIBRARYLIST                 1029
#define IDC_REPLACE_WITH                1029
#define IDC_HANDBOXLIST                 1030
#define IDC_KEYTEXT                     1039
#define IDC_DATA1TEXT                   1040
#define IDC_BUTTON_TOHBX_ALL            1040
#define IDC_DATA2TEXT                   1041
#define IDC_BUTTON_TOHBX_REFRESH        1041
#define IDC_DATA3TEXT                   1042
#define IDC_LABEL_SELECT                1042
#define IDC_DATA4TEXT                   1043
#define IDC_COMBO                       1043
#define IDC_DATA5TEXT                   1044
#define IDC_STATIC_PROMPT               1044
#define IDC_DATA6TEXT                   1045
#define IDC_CHECK_DELETE                1045
#define IDC_DATA7TEXT                   1046
#define IDC_CHECK_UPDATE                1046
#define IDC_DATA8TEXT                   1047
#define IDC_DATA9TEXT                   1048
#define IDC_LABEL_ALL                   1049
#define IDC_LABEL_REFRESH               1050
#define IDC_STATIC_SATELLITES           1052
#define IDC_LIST_SATELLITES             1053
#define IDC_STATIC_ALL                  1060
#define IDC_CHECK_ALL_ASTEROIDS         1061
#define IDC_CHECK_ALL_LANDMARKS         1062
#define IDC_CHECK_ALL_SATELLITES        1063
#define IDC_CHECK_ALL_TOURS             1064
#define IDC_CHECK_ALL_COMETS            1065
#define IDC_CHECK_ALL_USEROBJ           1066
#define IDC_CHECK_ALL_ALL               1067
#define IDC_DATA1LIMITS                 1079
#define IDC_DATA2LIMITS                 1080
#define IDC_DATA3LIMITS                 1081
#define IDC_DATA4LIMITS                 1082
#define IDC_DATA5LIMITS                 1083
#define IDC_DATA6LIMITS                 1084
#define IDC_DATA7LIMITS                 1085
#define IDC_DATA8LIMITS                 1086
#define IDC_DATA9LIMITS                 1087
#define IDC_STATIC_RANGE                1088
#define IDC_LOCAL_VERS                  1089
#define IDC_BUTTON_CHECK_WWW            1090
#define IDC_STATIC_HD_WARNING           1091
#define IDC_TREE_SATELLITES             1092
#define IDC_RICHEDIT_LOG                1093
#define IDC_UPGRADE_TYPE                1096
#define IDC_REALTIME                    1097
#define IDC_UPGRADE_ERASE               1098
#define IDC_STATIC_DATE                 1099
#define IDC_FIELD_LIST                  1106
#define IDC_FIELD_ADD                   1107
#define IDC_FIELD_REMOVE                1108
#define IDC_STATIC_FIELD                1109
#define IDC_EDIT_FIELD                  1110
#define IDC_EDIT_CATNAME                1111
#define IDC_LIST_USERSITE               1112
#define IDC_BUTTON_SITE_ADD             1113
#define IDC_BUTTON_SITEDELETE           1114
#define IDC_BUTTON_SITEEDIT             1115
#define IDC_EDIT_USERNAMEFIRST          1116
#define IDC_EDIT_USERNAMELAST           1117
#define IDC_EDIT_USERSTREET1            1118
#define IDC_EDIT_USERSTREET2            1119
#define IDC_EDIT_USERCITY               1120
#define IDC_EDIT_USERSTATE              1121
#define IDC_EDIT_USERPOST               1122
#define IDC_EDIT_USERSERIAL             1123
#define IDC_STATIC_SERIALNUM            1123
#define IDC_EDIT_USERPIN                1124
#define IDC_CHECK_PEC                   1124
#define IDC_EDIT_USERDOBMON             1125
#define IDC_EDIT_USERDOBDAY             1126
#define IDC_EDIT_USERDOBYR              1127
#define ID_COMBOTYPE                    2000
#define ID_COMBOSTATIC                  2001
#define ID_BUTTONDELETE                 2002
#define ID_EDIT_EDIT                    2003
#define ID_EDIT_DELETE                  2004
#define ID_EDIT_NEW                     2005
#define ID_EDIT_CLEAR_LIB               2006
#define ID_EDIT_CLEAR_HBX               2007
#define IDC_STATIC_LIBRARY1             2010
#define IDC_STATIC_LIBRARY2             2011
#define IDC_STATIC_HANDBOX1             2012
#define IDC_STATIC_HANDBOX2             2013
#define ID_OPTIONS_RECENT               2020
#define ID_OPTIONS_CONNECT              2021
#define ID_OPTIONS_ADVANCED             2022
#define ID_OPTIONS_VERIFY               2023
#define ID_OPTIONS_RETRIEVE             2024
#define ID_OPTIONS_COMPORT              2025
#define ID_OPTIONS_BACKGROUND_RESET     2026
#define ID_OPTIONS_GC                   2027
#define ID_OPTIONS_BACKGROUND           2028
#define ID_BUTTONUPDATE                 2030
#define ID_FILE_WWW_ALL                 2040
#define ID_FILE_WWW_COMETS              2041
#define ID_FILE_WWW_SATELLITES          2042
#define ID_FILE_WWW_ASTEROIDS_DISTANT   2043
#define ID_FILE_WWW_ASTEROIDS_BRIGHT    2044
#define ID_FILE_WWW_ASTEROIDS_NEO       2045
#define ID_FILE_WWW_ASTEROIDS_CRITICAL  2046
#define IDC_COM1                        2050
#define IDC_COM2                        2051
#define IDC_COM3                        2052
#define IDC_COM4                        2053
#define IDC_COM_OTHER                   2054
#define IDC_COMPORT_AUTO                2055
#define IDC_COM_EDIT                    2056
#define IDC_EDIT1                       2060
#define IDC_EDIT2                       2061
#define IDC_EDIT3                       2062
#define IDC_EDIT4                       2063
#define IDC_EDIT5                       2064
#define IDC_EDIT6                       2065
#define IDC_EDIT7                       2066
#define IDC_EDIT8                       2067
#define IDC_EDIT9                       2068
#define IDC_EDIT10                      2069
#define ID_STATUSBAR                    2080
#define ID_OPTIONS_BAUD_115K            2089
#define ID_OPTIONS_BAUD_56K             2090
#define ID_OPTIONS_BAUD_38K             2091
#define ID_OPTIONS_BAUD_28K             2092
#define ID_OPTIONS_BAUD_19K             2093
#define ID_OPTIONS_BAUD_14K             2094
#define ID_OPTIONS_BAUD_9600            2095
#define IDC_BUTTON_SELECT               2199
#define IDC_USEROBJ                     2200
#define IDC_USEROBJ20                   2201
#define IDC_USEROBJ21                   2202
#define IDC_USEROBJ22                   2203
#define IDC_USEROBJ23                   2204
#define IDC_USEROBJ24                   2205
#define IDC_USEROBJ25                   2206
#define IDC_USEROBJ26                   2207
#define IDC_USEROBJ27                   2208
#define IDC_USEROBJ28                   2209
#define IDC_USEROBJ29                   2210
#define IDC_USEROBJ30                   2211
#define IDC_USEROBJ31                   2212
#define IDC_USEROBJ32                   2213
#define IDC_USEROBJ33                   2214
#define IDC_USEROBJ34                   2215
#define IDC_USEROBJ35                   2216
#define IDC_USEROBJ36                   2217
#define IDC_USEROBJ37                   2218
#define IDC_USEROBJ38                   2219
#define IDC_USEROBJ39                   2220
#define IDC_USEROBJ40                   2221
#define IDC_LASTEROIDSRADIO             2300
#define IDC_LCOMETSRADIO                2301
#define IDC_LSATELLITESRADIO            2302
#define IDC_LUSEROBJECTSRADIO           2303
#define IDC_LLANDMARKSRADIO             2304
#define IDC_LTOURSRADIO                 2305
#define IDC_HASTEROIDSRADIO             2306
#define IDC_HCOMETSRADIO                2307
#define IDC_HSATELLITESRADIO            2308
#define IDC_HUSEROBJECTSRADIO           2309
#define IDC_HLANDMARKSRADIO             2310
#define IDC_HTOURSRADIO                 2311
#define ID_VIEW_ADVANCED                32771
#define ID_FILE_IMPORT                  32772
#define ID_FILE_EXPORT                  32773
#define ID_CONTEXT_DELETE               32780
#define ID_CONTEXT_NEW                  32781
#define ID_CONTEXT_EDIT                 32782
#define ID_IMPORT_SATELLITE             32783
#define ID_IMPORT_COMET                 32784
#define ID_IMPORT_LANDMARK              32785
#define ID_IMPORT_TOUR                  32786
#define ID_IMPORT_USEROBJECT            32787
#define ID_IMPORT_ASTEROID              32788
#define ID_BUTTON_OPEN                  32789
#define ID_FILE_SAVE_HBX                32790
#define ID_BUTTON_WWW                   32791
#define ID_FILE_OPEN_HBX                32791
#define ID_FILE_RESTORE                 32792
#define ID_BUTTON_CONNECT               32793
#define ID_BUTTON_EDIT                  32794
#define ID_BUTTON_NEW                   32795
#define ID_BUTTON_BLANK                 32796
#define ID_FILE_WWW_TOURS               32810
#define ID_FILE_WWW                     32813
#define ID_TOOLS_GC                     32823
#define ID_TOOLS_RESET                  32824
#define ID_TOOLS_USERSITE               32825
#define ID_INDICATOR_MODEL              59142
#define ID_INDICATOR_HBX                59143
#define ID_INDICATOR_MEM                59144
#define ID_INDICATOR_VER                59145
#define ID_INDICATOR_STATUS             59146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
